### PR TITLE
remove matsci channel, because main pkgs merge to forge

### PR DESCRIPTION
**Pull request by specter119**
I requested the anaconda mirror and mentioned the matsci channel for our materials-project packages. But now, the main packages of materials-project have been merged into the conda-forge channel, I'm convinced that I have no longer need matsci channel, so I remove it from the sjtug.

Maybe you also need to remove the files manually.

### CODE REVIEW

**Comment by htfy96** [comment]
Hi,

Thanks for your contribution! I was wondering if matsci will continue to be maintained, or it is deprecated? There might be others depending on matsci to work in this case, so we probably can't remove it right now.

**Comment by specter119** [comment]
In their home page, they have officially change the installation command to
`conda install --channel conda-forge XXX`
I think they will no longer maintain the matsci channel. Besides,  as a daily user, I have tried to remove the matsci for months, everything works well as expected.

**Comment by specter119** [comment]
matsci is really safe to be removed.
Also, I found the soumith(which used to provide pytorch) should be replace by pytorch. It seems that this channel also stop maintaining for a long time.

**Review by skyzh — APPROVED** [review]

**Comment by skyzh** [comment]
Thank you for your contribution!

**Comment by skyzh** [comment]
I can't believe that I found a PR not merged half a year ago...

**Comment by specter119** [comment]
@skyzh 我发现服务器上这几个新加的 channel 都还木有？

**Pull request merged**
